---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "deployment-1"
  namespace: "default"
  labels:
    app: "deployment-1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "deployment-1"
  template:
    metadata:
      labels:
        app: "deployment-1"
    spec:
      containers:
      - name: "nginx-sha256-1"
        image: "europe-west2-docker.pkg.dev/tcs-demo-448312/tcs-docker-demo/nginx:latest"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "deployment-1-hpa-jb9y"
  namespace: "default"
  labels:
    app: "deployment-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "deployment-1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "deployment-1-service"
  namespace: "default"
  labels:
    app: "deployment-1"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "deployment-1"
  type: "LoadBalancer"
  loadBalancerIP: ""
