apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: my-gke-cluster   # Name of the cluster
  namespace: config-connector   # Ensure this namespace exists
spec:
  location: europe-west1     # Specify the region or zone
  initialNodeCount: 2       # Number of initial nodes
  nodeConfig:
    machineType: e2-micro  # Machine type for nodes
    diskSizeGb: 10         # Disk size per node
    oauthScopes:            # Scopes for node access
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/devstorage.read_only
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring
  networkRef:
    name: default           # Use the default VPC network
  subnetworkRef:
    name: default           # Use the default subnetwork
  releaseChannel: STABLE    # Options: RAPID, REGULAR, STABLE
  workloadIdentityConfig:
    identityNamespace: "my-project.svc.id.goog"  # Replace with your project ID

---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: my-gke-node-pool
  namespace: config-connector
spec:
  clusterRef:
    name: my-gke-cluster
  location: europe-west1
  initialNodeCount: 2
  nodeConfig:
    machineType: e2-micro
    diskSizeGb: 10
    oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/devstorage.read_only
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring
