name: Deploy Nginx

on:
  push:
    branches:
    - 'main'

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: src
          framework: terraform 
    
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_TCS }}'

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GCP_TCS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image to repo
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker europe-west2-docker.pkg.dev
        docker build -t europe-west2-docker.pkg.dev/tcs-lab-447919/tcs-docker-demo/nginx:latest .
        docker push europe-west2-docker.pkg.dev/tcs-lab-447919/tcs-docker-demo/nginx:latest

    - name: deploy the docker image to gke
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud container clusters get-credentials tcs-demo-gke --region europe-west1
        kubectl apply -f ./deploy-image.yml
