name: Deploy Nginx 

on:
  push:
    branches:
    - 'main'

jobs:
  scan-deployment-code:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./
          framework: terraform 
  
  deploy-nginx-docker-image: 
   #needs: scan-deployment-code
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2  
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_TCS }}'
  
  setup-environment:
    runs-on: ubuntu-latest
    needs: deploy-nginx-docker-image
    steps:
      - name: Deploy gcloud utils and authenticate github
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GCP_TCS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true
          
  build-image:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Build and push the nginx docker image to Artifact Registry
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker europe-west2-docker.pkg.dev
          docker build -t europe-west2-docker.pkg.dev/tcs-demo-448312/tcs-docker-demo/nginx:latest .
          docker push europe-west2-docker.pkg.dev/tcs-demo-448312/tcs-docker-demo/nginx:latest
         # europe-west2-docker.pkg.dev/tcs-demo-448312/tcs-docker-demo

  deploy-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Deploy the docker image to Kubernetes environment
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud container clusters get-credentials tcs-demo-gke --region europe-west2
          kubectl apply -f ./deploy-image.yml
